sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        PTrv6fZ8+3Ryxi94XIKt6Z90yheV6zgEoCTC2k5aBRll8sPN/AmTYlXXUWAMBtccLEiaCJGeGfjRaYwqetYm4nTvEInBFNKSIxbGL4qF74LT6MkLs/f2a3+vv1Qbo7m5D6E3ZggMYy8jzMWvungiWGZhniqvXNQthSm2ceF5Fdoo1RJo5ci2QDvsMTxGIpvaMjqNTcUaDQ9RfNTe8e1HLpCALlW+fvhxbEoLl8ndG2VBrAvzcqT16OHyeikL/RxZFdm4DDCj5MWURqmacmYsZPJyPyNA4t6FRG+6AmhJflA888dzacJo6k2rCcb2FQOE4uAUhRabUUqJctNu2Q3QoLXOgtoDfff6JupMNd0ewisczyswxziRxXi8zKg+75L1hkcFnG6M3ShzyrMNdn42USAjiszeaz5KC61ZR9hvRQdyqNMPH0KVQmO3gDyst6pk7Sii7gth7qOsOWMmgxNJSjbsJb3z9eUP93bOgehK6hPDQWx4aWtXHmZ34dzZGOgnIpvahTAQOjUM2E/VcL4pGAG3jISZq/J0a9Rdr/o+KMc+/QJgAcefq9O44T8gZwthcGWnpclugLyzQfcnYCps9hehF3nznj0Y+y5LI1hBCLS5LXNhJjleZilWUUvvGdEx7fZS52Bf6CBB+mLgHwFpnwH3WW3n4+xVxHKcGd2d2JI=
    - secure: >-
        DcE34UGY4+Hv8doiQK/il5lcoSS8A7SXf1C9Im4EcO3vkN4bBbT7q60yzT5bFJZOihhuU5BLsNINTFF4HTtpCbUv6fdHnmXV0Wxt5m2nTy1yf2kVyz7RXfQMYtqPeGowdKlhLmIMVHoubZqWuxZT0dZLTdAshwYm0AOihvw+zrR0CAC/yLvKIL+RWy37+AJj68V1/uYThL/cKd3kON+CyERFhHhPnUrjSeDqmxR6NJgRF+TnguWpNFo2IQ2jUD6iGZwX403ExY4K9JENYd1UEZAD6E/lpkVQ6EmC5GqmjdH3k+MYrR+ykDylwY6DFItDBW7UVBgqzE2VLn1qdQ2SJE6HvtqK4c20M6DsMJ8n7juJsTKiEN9rFwWwGzP+xJeeXSbFCB+3hOfZ1LfZWb0xq/6DCKfu+63ndVYlFt2D154yY2UXW/4KggcRt4/4WvRk1SdZxoZB3ow5VAXrfI4ZHj/KUxIiV29Gbu3ECAoNdnYyqBlEx4lsUHpB+SZVIHflh9YsqV18osXTN2QrO05F1omSgeSjK3Y/vEPBxjW3fApPrNLzB5/eImwex3wYA/Y6hkhNnxxLS4paJ0RiojpShcqLddHZhfbIkU37fP7+AfDwYK0VPnmOeXXsG7n21gcKO2u6olovPbKiOhYLw36DSI8EupReNGPOq05Uko5E5+A=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
